- name: Install and configure Nginx
  hosts: aws
  become: yes

  tasks:
    - name: Install Nginx package
      apt:
        name: nginx
        state: present

    - name: Copy nginx.conf
      copy:
        src: /home/server/ansible-hexlet/files/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Copy modified index.html
      template:
        src: /home/server/ansible-hexlet/files/index.html.j2
        dest: /var/www/html/index.html
      notify: Restart Nginx service

  handlers:
    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted

